#%RAML 1.0
---

title: National Insurance Record
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/securitySchemes.raml
  headers: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/headers.raml
  annotations: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/annotations.raml
  types: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/types.raml

traits:
  errorResponses:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              invalidNino:
                description: Invalid NINO
                value:
                  code: ERROR_NINO_INVALID
              badRequest:
                description: Bad request
                value:
                  code: BAD_REQUEST
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              exclusionManualCorrespondence:
                description: Manual correspondence exclusion
                value:
                  code: EXCLUSION_MANUAL_CORRESPONDENCE
              exclusionDead:
                description: Death recorded
                value:
                  code: EXCLUSION_DEAD
              exclusionIsleOfMan:
                description: Isle of Man exclusion
                value:
                  code: EXCLUSION_ISLE_OF_MAN
              exclusionMarriedWomensReducedRate:
                description: Married women reduced rate exclusion
                value:
                  code: EXCLUSION_MARRIED_WOMENS_REDUCED_RATE
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFound:
                description: NINO not found
                value:
                  code: NOT_FOUND


/national-insurance-record:
  /ni:
    /{nino}:
      uriParameters:
        nino:
          description: A valid National Insurance number
          type: string
          example: QQ123456A
      get:
        displayName: Get National Insurance summary
        description: Returns a National Insurance statement
        is:
          - headers.acceptHeader
          - errorResponses
        (annotations.scope): "read:national-insurance-record"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:national-insurance-record" ] } ]
        (annotations.sandboxData): !include sandbox/sandbox.md
        responses:
          200:
            body:
              application/json:
                type: !include schemas/national-insurance-summary.json
                example: !include examples/national-insurance-record-example-1.json

      /taxyear:
        /{taxYear}:
          uriParameters:
            taxYear:
              description: A valid tax year
              type: string
              example: "2010-11"
          get:
            displayName: Get National Insurance tax year statement
            description: Returns a National Insurance tax year statement
            is:
              - headers.acceptHeader
              - errorResponses
            (annotations.scope): "read:national-insurance-record"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:national-insurance-record" ] } ]
            (annotations.sandboxData): !include sandbox/sandbox.md
            responses:
              200:
                body:
                  application/json:
                    type: !include schemas/national-insurance-taxyear.json
                    example: !include examples/national-insurance-taxyear-example-1.json
